# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu -sv +define+COCOTB_SIM=1 +acc  tb_matraptor_core.sv Matraptor.sv simple_spi_interface.sv
vsim -l sim.log   -onfinish exit -pli /u/abhimusk/.local/lib/python3.6/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.tb_matraptor_core
onbreak resume
run -all
quit
